sequence:
  - step_name: handshake_ready
    target_xyz_mm: [-300.0, -300.0, 300.0]
    target_rpy_deg: [90.0, 0.0, 0.0]
    seed_joints_deg: [-130.0, -90.0, -120.0, 200.0, -120.0, 0.0]
    execute: true
    max_velocity_scale: 0.12
    max_acceleration_scale: 0.12
    print_joints: true

  - step_name: handshake_forward
    target_xyz_mm: [-300.0, -300.0, 200.0]
    target_rpy_deg: [90.0, 0.0, 0.0]
    seed_joints_deg: [-130.0, -90.0, -120.0, 200.0, -120.0, 0.0]
    execute: true
    max_velocity_scale: 0.10
    max_acceleration_scale: 0.10
    print_joints: true